language: node_js

node_js:
  - 'node'

addons:
  code_climate:
    repo_token: 06de2a8b6aa7f51643a9007bc61b4cc13673e8ab5749a8768d9695417359374a

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  - npm install codeclimate-test-reporter
  
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
